// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSDUc85cjLiXkU0R1rpBEHzZMKDMCBPlU',
    appId: '1:906066155445:web:90c7a7a34802e0c9afabfc',
    messagingSenderId: '906066155445',
    projectId: 'medlink-d0895',
    authDomain: 'medlink-d0895.firebaseapp.com',
    storageBucket: 'medlink-d0895.firebasestorage.app',
    measurementId: 'G-YHX8T2PQ0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw8SSOMW8kfXgRLCUM5AFj7oor2MMNgII',
    appId: '1:906066155445:android:b280d92bf35cc775afabfc',
    messagingSenderId: '906066155445',
    projectId: 'medlink-d0895',
    storageBucket: 'medlink-d0895.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRKpD-irDzISIPDVzvu9NQMYMBhTykwhE',
    appId: '1:906066155445:ios:078c56b54ef78808afabfc',
    messagingSenderId: '906066155445',
    projectId: 'medlink-d0895',
    storageBucket: 'medlink-d0895.firebasestorage.app',
    iosBundleId: 'com.example.medlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRKpD-irDzISIPDVzvu9NQMYMBhTykwhE',
    appId: '1:906066155445:ios:078c56b54ef78808afabfc',
    messagingSenderId: '906066155445',
    projectId: 'medlink-d0895',
    storageBucket: 'medlink-d0895.firebasestorage.app',
    iosBundleId: 'com.example.medlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSDUc85cjLiXkU0R1rpBEHzZMKDMCBPlU',
    appId: '1:906066155445:web:53871c4e3ae0aff2afabfc',
    messagingSenderId: '906066155445',
    projectId: 'medlink-d0895',
    authDomain: 'medlink-d0895.firebaseapp.com',
    storageBucket: 'medlink-d0895.firebasestorage.app',
    measurementId: 'G-DRN8FB4V39',
  );
}
